install:
  - sudo pip install proselint

script: 
  - proselint README.md
  - proselint Faq.md
  - cd hello
  - ./test_tests
  - cd ..
  - cd hello_world
  - ./test_tests
  - cd ..
  - cd hello_cli
  - ./test_tests
  - cd ..
  - cd is_odd
  - cp accept_0.cpp main.cpp; ./build; ./test
  - ./test_tests
  - cd ..

